### PR TITLE
Added Linked List Creation and Traversal in Java

### PR DESCRIPTION
**Pull request by hardiktaluja**

### CODE REVIEW

**Comment by hardiktaluja** [comment]
@Anishukla I have a great idea of creating separate projects and subfolders as per languages in each folder so that anyone can just go into the Language of their choice, and will be able to import the project directly instead of just files.
Also, Please review and merge.

**Comment by Anishukla** [comment]
Thanks for contributing!

**Comment by Anishukla** [comment]
Your idea is quite impressive. It will be great if you can help me with your idea by doing the needful(if possible). As I'm getting too many pull requests which I have to review. Thanks in advance!

**Comment by hardiktaluja** [comment]
Thanks for merging @Anishukla 
Sure, I will start the project creation process and will send the PR, then everyone can contribute the on the same.

**Comment by hardiktaluja** [comment]
@Anishukla The repo is missing the hacktoberfest label. Please add the same to the repo also so that more people can also contribute, and repo is highly visible.

**Pull request merged**
